[package]
name = "podgpt"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = "0.28.0"
poise = "0.6.1"
serenity = "0.12.4"
serenity-commands = "0.8.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
